### ISSUE TITLE
Response failure, cause: Failed to connect to bypass.duti.tech/127.0.0.1:443, please try again.

### ISSUE THREAD

**Issue by MohammadRaziei** [dromara/ChatGPT#159] opened 2023-04-02 17:16 UTC
hi I have this issue:

Response failure, cause: Failed to connect to bypass.duti.tech/127.0.0.1:443, please try again.

Tips: if proxy is enabled, please check if the proxy server is working.

But I set no global proxy on my computer

**Comment by senflyboy** [comment] 2023-04-03 01:02
me too

**Comment by obiscr** [comment] 2023-04-03 01:16
Indeed, the third party service is not available anymore. Working on a solution.

Also this issue is a duplicate of #150. Stay tuned to #150 for subsequent updates.

**Closed by obiscr** 2023-04-03 01:16 UTC
Labels: duplicate
