### ISSUE TITLE
login fail

### ISSUE THREAD

**Issue by zjz2009000** [dromara/ChatGPT#165] opened 2023-04-04 03:13 UTC
I find this when login:
![image](https://user-images.githubusercontent.com/20659728/229677752-655fe865-9b24-4ac7-9907-d4924f73005a.png)
And I checked the idea.log it looks like this:
![image](https://user-images.githubusercontent.com/20659728/229678028-0fc8e1ad-ea5d-4b8b-8bd4-5586f8b6f1ed.png)
Is some thing wrong?

**Comment by obiscr** [comment] 2023-04-04 07:38
Yes, as you can see, it does not work, more information can be found at #150. Also this is a duplicate of #150. Please discuss the follow up progress at #150. Thanks!

**Closed** 2023-04-04 07:38 UTC
